#!/usr/bin/env node

var opts = require('./src/cli/parse_args.js')()
  .option('f', {
    type: 'flag'
  })
  .option('m', {
    type: 'flag' // minimal build
  })
  .parse(process.argv.slice(2));

var fs = require('fs');
var _ = require('underscore');
var path = require('path');
var rollup = require('rollup');
var rollupWatch = require('rollup').watch;
var getRollupConfig = require('./rollup.config.js');
var deps, ofile;

if (opts._.length > 0) {
  deps = getRequestedDeps(opts._[0].split(','));
}

if (opts.m) {
  ofile = "mproj-minimal.js";
} else if (deps) {
  ofile = "mproj-custom.js";
} else {
  ofile = "mproj.js";
}

if (!deps) {
  deps = getAllDeps();
}

runBuild().catch(function(err) {
  console.error(err.message || err);
  process.exit(1);
});

async function runBuild() {
  var cfg = getRollupConfig({
    minimal: !!opts.m,
    deps: deps,
    outBase: ofile.replace(/\.js$/, '')
  });

  if (opts.f) {
    startWatch(cfg);
  } else {
    await writeBuild(cfg);
  }
}

function startWatch(cfg) {
  var watcher = rollupWatch(cfg);
  watcher.on('event', function(event) {
    if (event.code == 'ERROR') {
      console.error(event.error && event.error.message || event.error);
      return;
    }
    if (event.code == 'BUNDLE_END') {
      console.error('Wrote ' + path.relative(process.cwd(), event.output[0]));
      return;
    }
    if (event.code == 'END') {
      console.error('Watching for changes...');
    }
  });
}

async function writeBuild(cfg) {
  for (var i = 0; i < cfg.length; i++) {
    var item = cfg[i];
    var bundle = await rollup.rollup(item);
    await bundle.write(item.output);
    await bundle.close();
    console.error('Wrote ' + path.relative(process.cwd(), item.output.file));
  }
}

function getRequestedDeps(projs) {
  var index = {};
  var deps = [];
  var missing = [];
  getAllDeps().forEach(function(name) {
    findProjNames(name, index);
  });
  projs.forEach(function(proj) {
    if (proj in index) {
      deps.push(index[proj]);
    } else {
      missing.push(proj);
    }
  });
  if (missing.length > 0) {
    console.error("Missing:", missing.join(','));
    process.exit(1);
  }
  return _.uniq(deps);
}

function getAllDeps() {
  var deps = fs.readdirSync('src/projections').map(function(f) {
    var match = /(.*)\.js$/.exec(f);
    return match ? match[1] : null;
  });
  return _.compact(deps);
}

function findProjNames(fileName, index) {
  var argsRx = /pj_add\(([^;]+)/g;
  var trimRx = /['"\s]/g;
  var filePath = path.join('src/projections', fileName + '.js');
  var js = fs.readFileSync(filePath, 'utf8');
  var args, m;
  while (m = argsRx.exec(js)) {
    args = m[1].split(',');
    index[args[1].replace(trimRx, '')] = fileName;
  }
}
